version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      maven-dependencies:
        patterns:
          - "*"


  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"